version: 2.1

executors:
  machine-executor:
    machine:
      image: ubuntu-1604:202104-01

jobs:
  build:
    executor:
      name: machine-executor
    steps:
      - checkout
      - run:
          name: Build Docker containers
          command: |
            set -x
            docker-compose build
      - run:
          name: Mix deps.get & compile
          command: |
            set -x
            docker-compose run --rm app bash -c "mix deps.get && mix deps.compile"
      - run:
          name: Run Docker containers
          command: |
            set -x
            docker-compose up -d
            sleep 5
            docker ps -f status=running
            docker-compose logs
      - run:
          name: Mix test
          command: |
            set -x
            docker-compose exec app bash -c "mix test"
      - run:
          name: Finish build
          command: |
            set -x
            echo "Finish build"
